// Draws the favicon and the home-screen icons from the one Monstera leaf in
// src/monstera.js, so they always match the mark in the dashboard's header.
// The leaf is Delapouite's, under CC BY 3.0; see src/monstera.js.
//
//   npm run icons
//
// Run it after changing the leaf, and commit what it writes. Each target needs
// a different shape of the same icon:
//
//   favicon.svg             rounded badge, transparent corners
//   icons/icon-192, -512    the same badge, for Android's "any" purpose
//   apple-touch-icon        a full square: iOS rounds the corners itself, and
//                           paints anything transparent black
//   icons/icon-maskable-512 a full square with the leaf inside the central
//                           circle, 80% across, that every launcher mask keeps
import sharp from 'sharp';
import { writeFile } from 'node:fs/promises';
import { MONSTERA_CREDIT, monsteraLeaf } from '../src/monstera.js';

// A green leaf on the pale green of the header's mark, so the tab and the page
// show the same logo. Cream on green read as a cut-out, not a leaf.
const GREEN = '#2f7d32';
const PALE = '#e8f1e0';
const PUBLIC = new URL('../public/', import.meta.url);

const svg = (body) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">${body}</svg>`;
const leaf = (scale) => monsteraLeaf({ fill: GREEN, scale });

const badge = svg(`<rect width="64" height="64" rx="16" fill="${PALE}"/>${leaf(0.84)}`);
const square = svg(`<rect width="64" height="64" fill="${PALE}"/>${leaf(0.84)}`);
const maskable = svg(`<rect width="64" height="64" fill="${PALE}"/>${leaf(0.64)}`);

// A filled badge rather than a bare outline: at 16px a silhouette survives and
// hairlines do not.
await writeFile(
    new URL('favicon.svg', PUBLIC),
    badge.replace(
        '<svg ',
        `<!-- ${MONSTERA_CREDIT}. Generated by scripts/icons.mjs from src/monstera.js; edit those, not this. -->\n<svg role="img" aria-label="Monstera leaf" `,
    ) + '\n',
);

// Rendered at the size it is drawn, not scaled down from a large bitmap.
const png = (source, size, file) =>
    sharp(Buffer.from(source), { density: (72 * size) / 64 })
        .resize(size, size)
        .png({ compressionLevel: 9 })
        .toFile(new URL(file, PUBLIC).pathname);

await Promise.all([
    png(badge, 192, 'icons/icon-192.png'),
    png(badge, 512, 'icons/icon-512.png'),
    png(square, 180, 'apple-touch-icon.png'),
    png(maskable, 512, 'icons/icon-maskable-512.png'),
]);
console.log('icons: wrote favicon.svg, apple-touch-icon.png and icons/*.png');
